export interface AnnualFundamental {
  annaulFundamentalId?: number,
  turnover?: number,
  turnoverGrowthOneYear?: number,
  turnoverEmployee?: number,
  bookvaluePerShare?: number,
  bookvaluePriceRatio?: number,
  balanceSheetTotal?: number,
  balanceSheetEquityRatio?: number,
  balanceSheetEquityDept?: number,
  balanceSheetEquityDynamicDept?: number,
  accountingMethod?: string,
  marketCapitalization?: number,
  marketCapitalizationTurnover?: number,
  marketCapitalizationEmployee?: number,
  marketCapitalizationEbitda?: number,
  roiCashflowMarge?: number,
  roiEbitMarge?: number,
  roiEbitdaMarge?: number,
  roiEquity?: number,
  roiTotalCapital?: number,
  roiCashflow?: number,
  roiTaxQuote?: number,
  yearValue?: number,
  stockId?: number
}
